# Generated by Django 5.1.2 on 2024-10-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='product_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
