# Generated by Django 5.1.2 on 2024-10-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subcategory_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='categroy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categorymaster'),
        ),
    ]
