# Generated by Django 5.1.2 on 2024-10-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_categorymaster_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaster',
            name='manager_approval',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
