# Generated by Django 5.1.1 on 2024-10-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_categorymaster_manager_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymaster',
            name='manager_approval',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='manager_approval',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='product',
        ),
    ]
