# Generated by Django 5.1.1 on 2024-10-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_cart_price_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
