# Generated by Django 5.1.1 on 2024-10-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_name_iumaster_host_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleMaster',
            new_name='role_master',
        ),
        migrations.RenameModel(
            old_name='UserRoleMapping',
            new_name='user_rolemapping',
        ),
    ]
