# Generated by Django 5.1.1 on 2024-10-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_rolemaster_role_master_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='role_master',
            new_name='RoleMaster',
        ),
        migrations.RenameModel(
            old_name='user_rolemapping',
            new_name='UserRoleMapping',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
        migrations.AlterModelTable(
            name='iumaster',
            table='iu_master',
        ),
        migrations.AlterModelTable(
            name='rolemaster',
            table='role_master',
        ),
        migrations.AlterModelTable(
            name='userrolemapping',
            table='user_rolemapping',
        ),
    ]
