# Generated by Django 5.1.1 on 2024-10-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_sellerregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregistration',
            name='seller_status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
