# Generated by Django 5.1.1 on 2024-10-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_sellerregistration_rejection_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
