# Generated by Django 5.1.1 on 2024-10-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_customuser_last_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login_role',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
