# Generated by Django 5.1.2 on 2024-10-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_customuser_last_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
